### ISSUE TITLE
is_address is not working

### ISSUE THREAD

**Issue by geethsameer686** [primal100/pybitcointools#10]
I am validating with testnet address using 'is_address' method. This function is returning true even I change the address. Please fix this.

**Comment by primal100** [comment]
Hey

Can't you give an example of an address which is failing?

**Comment by geethsameer686** [comment]
from cryptos import *
b = Bitcoin()
# 1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdSg  -------- valid address
b.is_address('1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdSg') # return True
#1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdS----------- invalid address
b.is_address('1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdS') # returns True but it should return False

**Comment by primal100** [comment]
It only checks the first digit, it doesn't check the checksum (which is the way it worked in the original pycryptotools).. It's more of an internal convenience method for now but yes it could be improved.

For now you can use combineb. is_address (to check the prefix) with b.addrtoscript to check the checksum,  catching the AssertionError for bad checksums.

**Comment by geethsameer686** [comment]
Great. I hope it will be improved in the future. Thanks a lot
