### ISSUE TITLE
Problem from first examle in README

### ISSUE THREAD

**Issue by teror4uks** [primal100/pybitcointools#14]
Hello, I want to use your fork, for understand how works bitcoin net. And when I start generate inputs from https://github.com/primal100/pybitcointools#example-usage---the-long-way-best-way-to-learn-- that tutorial, I got a problem in my `inputs` always is empty list without value and output keys. And I don't understand it's normal or not? 

P.S. Sorry for my English.

**Comment by ArashFatahzade** [comment]
Hi, I have the same problem.
 `inputs` are like this: 
```{json}
[
  {
    'address': '1B9Ckk6EdwKSXRdCR1VVhtRtVrHFLvqCby',
    'height': 518447,
    'tx_hash': '171d20968d3adc4e4be7bd0689d6cacc197351cbfa29b23bea830620fe649e0b',
    'tx_pos': 2,
    'value': 18100000
  }
]
```
And the `is_inp` method searching for `output` or `outpoint` field in inputs but it is not there.
(Sorry for my bad English)

**Comment by primal100** [comment]
Should work now in the latest version 2.0.4.
