### ISSUE TITLE
Bitcoin Cash why bcc? Need BCH

### ISSUE THREAD

**Issue by maxclax** [primal100/pybitcointools#17]
MaxRetryError

HTTPSConnectionPool(host='bcc.blockdozer.com', port=443): Max retries exceeded with url: /insight-api/addrs/1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdSg/utxo (Caused by SSLError(CertificateError("hostname 'bcc.blockdozer.com' doesn't match either of 'bch.blockdozer.com', 'beta.blockdozer.com', 'blockdozer.com', 'btc.blockdozer.com', 'tbch.blockdozer.com', 'tbtc.blockdozer.com', 'www.blockdozer.com', 'zcash.blockdozer.com'",),))

Trust bch.blockdozer.com

And after use https://bch.blockdozer.com/insight-api/addrs/1GnX7YYimkWPzkPoHYqbJ4waxG6MN2cdSg/utxo or bcc I have empty result from explorer. Why?

**Comment by primal100** [comment]
Should be working in new version 2.0.4.
