### ISSUE TITLE
Use same coin classes for testnet and mainnet

### ISSUE THREAD

**Issue by v1k45** [primal100/pybitcointools#2]
Ideally for development environment a user/developer it would be easier/ convenient if same API/modules ran the expected functions on testnet without modifying much code.

For example:

With different classes/modules you'd have to do this in all files:
```python
from cryptos import bitcoin
from cryptos import bitcoin_testnet


if settings.PRODUCTION:
    Bitcoin = bitcoin.Bitcoin
else:
    Bitcoin = bitcoin_testnet.Bitcoin

txdata = {...}
Bitcoin().pushtx(txdata)
```

With same classes a user can perhaps do something like this:
```python
from cryptos.bitcoin import Bitcoin

txdata = {...}
Bitcoin(testnet=not settings.PRODUCTION).pushtx(txdata)
```

What do you think about it?
Feel free to assign this issue to me.

**Comment by primal100** [comment]
Yeah that's a good idea. Do any of the other coins have testnets easily accessible with an explorer, other than Bitcoin?

**Comment by v1k45** [comment]
[chain.so](https://chain.so/api#networks-supported) supports BTC, LTC, DOGE and DASH for both, mainnet and testnet.

For Bitcoin cash we can use [Blockdozer](http://tbcc.blockdozer.com/insight/) which uses a fork of Bitpay's Insights API.

**Comment by primal100** [comment]
OK I changed to chain.io for those four. It's worth it to have mainnet and testnet support for those four coins. Test cases for Bitcoin testnet are ok, will try to do write tests for three testnets later today or tomorrow. 

For now I have put one module per coin, with mainnet and testnet classes in each module. So feel free to change it around if you have a preferred implemetation. Or add the blockdozer explorer api for Bitcoin Cash. For each explorer we really just need unspents and pushtx, anything else is a bonus.
