### ISSUE TITLE
Bug on rpc.py

### ISSUE THREAD

**Issue by iRhonin** [primal100/pybitcointools#22]
I think this two line is obviously incorrect in rpc.py file (line 97 and 100):
```
        if self.use_ssl and not 's' in server.keys():
```

```
        elif not self.use_ssl and not 't' in server.keys():
```

**Comment by Aareon** [comment]
```
>>> l = ['l', 'm', 'n']
>>> if True and not 's' in l:
...          print('works')
...
works
>>> not 's' in l
True
```
How are the above two lines incorrect?

**Comment by mehrdad1373pedramfar** [comment]
Actually it is not incorrect but the best practice is to write  `'s' not in l` instead of `not 's' in l`.

**Comment by Aareon** [comment]
Unrelated as this issue isn’t about best practice. OP opened this as a bug. However, this is not a bug.

**Comment by primal100** [comment]
Never knew about that being best practice. Both work anyway. I'm working on a rewrite of this in another branch so will have a look at it their.

**Comment by iRhonin** [comment]
Yeap both are the same.
