### ISSUE TITLE
DASH not working explorer

### ISSUE THREAD

**Issue by maxclax** [primal100/pybitcointools#28]
https://insight.dash.siampm.com/api back **Bad Request** !!!

**Comment by jesusdicaprio** [comment]
any solution for Dash?

**Comment by jesusdicaprio** [comment]
Solved changing the explorer for Dash. 
In file: /home/Personal_Folder/.local/lib/python3.6/site-packages/cryptos/coins/dash.py

-----------------------------------
from ..explorers import sochain

class Dash(BaseCoin):
    #explorer = dash_siampm
    explorer = sochain

**Comment by qari** [comment]
> changing



> Solved changing the explorer for Dash.
> In file: /home/Personal_Folder/.local/lib/python3.6/site-packages/cryptos/coins/dash.py
> 
> from ..explorers import sochain
> 
> class Dash(BaseCoin):
> #explorer = dash_siampm
> explorer = sochain

What do you change and integrate in application? When I get from github packet I have error

**Comment by primal100** [comment]
Should work now with electrumx (although there are very few Dash ElectrumX servers so may be unreliable).
