### ISSUE TITLE
AssertionError On Litecoin

### ISSUE THREAD

**Issue by samitabar** [primal100/pybitcointools#30]
Hi When i Try to Send Litecoin to other addresses i get an error 

assert bin_dbl_sha256(data[:-4])[:4] == data[-4:]
AssertionError

**Comment by Asidert** [comment]
> Hi When i Try to Send Litecoin to other addresses i get an error
> 
> assert bin_dbl_sha256(data[:-4])[:4] == data[-4:] AssertionError

What OS are you using? I have the same problem on Debian 11

**Comment by GhegethDev** [comment]
Have you able to resolved your issues

**Comment by naim-prog** [comment]
I'm having the exact same Issue when I try to send LTC from a p2pkh L-address to a native segwit bech32 address. Did you find the problem to that?

**Comment by hammersharkfish** [comment]
I have the same error with bc1 addresses

**Comment by hammersharkfish** [comment]
Did you find a solution ?

**Comment by primal100** [comment]
This should be working now latest version 2.0.4. Sorry for delay, I recently starting maintaining this library again after a few years.
