### ISSUE TITLE
Error on following readme and "cannot choose from empty sequence"

### ISSUE THREAD

**Issue by 701789262a** [primal100/pybitcointools#51]
I have 2 issues:

1. When literally copying the readme examples it appears that the parameters are given out of order and it tries to parse as int the recipient address.

2. Even when fixing the issue above (adding keyword arguments) it gives "IndexError: Cannot choose from an empty sequence"; as far as I can see it tries to select a random server from an empty list that should be filled by
```
        if servers:
            self.servers = servers
        else:
            self.servers = read_json(server_file, {})
```
in lines 68 to 71.

The server file "bitcoin.json" seems to not be present, and then defaults to empty.
Am I supposed to provide this file?

**Comment by primal100** [comment]
No, you don't have to provide that servrs.json file. Which lines in the README example are you having a problem with?

**Comment by 701789262a** [comment]
> No, you don't have to provide that servers.json file. Which lines in the README example are you having a problem with?

Trying to run:

```
c= Bitcoin(testnet=True)
tx = c.preparesignedtx(privkey="89d8d898b95addf569b458fbbd25620e9c9b19c9f730d5d60102abbabcb72678", addr="tb1qsp907fjefnpkczkgn62cjk4ehhgv2s805z0dkv", to="tb1q95cgql39zvtc57g4vn8ytzmlvtt43skngdq0ue", value=5000)
```


--
If I don't need to provide that file. why does it read empty?

**Comment by primal100** [comment]
gIt looks like the .json files were missing from the latest release. There is a new release out today, can you try upgrading to 2.0.7?

```shell
python -m pip install --upgrade cryptos==2.0.7
```

The README has been updated as well.
