### ISSUE TITLE
confirmations 0

### ISSUE THREAD

**Issue by qari** [primal100/pybitcointools#7]
I can't understand how can I send if I have 2 Inputs: first input has confirmations more 100 and second zero. How can I send it that my transactions will be done? I need sign all inputs or only where confirmations more?

**Comment by primal100** [comment]
Yes you need to sign all inputs regardless of the number of confirmations. You can spend inputs with 0 confirmations. However the transaction won't be confirmed until the previous transaction the inputs came from is confirmed.

**Comment by qari** [comment]
How I can check TX confirmed or not? How I can get number confirmations on TX?

**Comment by primal100** [comment]
```python
Bitcoin().fetchtx(txhash)
```

**Comment by qari** [comment]
But, when I use fetchtx() I get only block_height not N confirmations

**Comment by primal100** [comment]
You're right. Unfortunately we have to use different explorers for different coins and for whatever reason blockchain.info, the one we use for Bitcoin doesn't return confirmations. What you can do is

```python
coin = Bitcoin()
tx = coin.fetchtx(txhash)
tx_height = tx['block_height']
blockchain_height = coin.current_block_height()
confirmations = blockchain_height - tx_height + 1
```
