### ISSUE TITLE
Unite some addresses in one transaction

### ISSUE THREAD

**Issue by qari** [primal100/pybitcointools#9]
I have a little address when have confirmed inputs. I want to unite some addresses in one transaction for payment. How can I do it?

For examples:
Alice has inputs on her address and Bob has inputs on his address and they wanna send their inputs to Ivan address in once transaction for economy fees.

**Comment by primal100** [comment]
You can do it using mktx and then sign each input individually with the appropriate private key. For example:

```python
from cryptos import *
c = Bitcoin()
unspents1 = c.unspent('aliceaddr')
unspents2 =  c.unspent('bobaddr')
ins = unspents1 + unspents2
outs = [{address: 'ivansaddr', 'value': 1000000}, {'address': 'aliceaddr', 'value': 2000000}, {'address': 'bobaddr', 'value': 3000000}]
tx = c.mktx(ins, outs)
for i in range(0, len(unspents1)):
    c.sign(tx, i, 'aliceprivkey')
for i in range(len(unspents1), len(ins)):
   c.sign(tx, i, 'bobprivkey')
tx = serialize(tx)
c.pushtx(tx)
```

**Comment by qari** [comment]
If we have more address than two as sender, how can correct sign all?
It's only if two sender
for i in range(len(unspents1), len(ins)):

**Comment by primal100** [comment]
The code is in my original comment for two addresses, you can easily extend it to more than three. You need to know which private key can sign each input. Just sign them one by one if you need.
